config/routes.rb
Rails.application.routes.draw do
  root to: redirect('pos')

  get 'login' => 'session#login'
  post 'login' => 'session#auth'
  get 'logout' => 'session#logout'

  get 'orders' => 'orders#index'

  get 'pos' => 'pos#index'
  post 'pos' => 'pos#save', as: :save
  # edit
  get 'pos/edit/:id' => 'pos#edit', as: :edit_order
  # JSON
  get 'pos/products' => 'pos#products'
  get 'pos/combos' => 'pos#combos'
  # view details & print reciept
  get 'orders/:id' => 'orders#view', as: :view_order
  post 'orders/:id/pay' => 'orders#pay', as: :pay_order
  post 'orders/:id/ship' => 'orders#ship', as: :ship_order
  delete 'orders/:id/refund' => 'orders#refund', as: :refund_order

  get 'admin' => 'admin#index'

  scope 'admin' do
    get 'dashboard' => 'admin#dashboard'
    resources :users, :products, :combos, :stocks
  end

  # TODO: group together with resources:products
  get 'products/images/:id' => 'products#img', as: :product_img
  # TODO: combo_img
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  scope :paid, -> { where.not(paid_at: nil) }
  has_many :stocks, dependent: :destroy

  # TODO: use json or serialize :cart, OpenStruct (and customer info)

  # TODO: what will happen if a product is deleted or price is changed?

  # TODO: cache `bought` and `received`

  def bought
    cart = JSON.parse(self.cart, object_class: OpenStruct)
    count = Hash.new(0)
    cart.items.each do |item|
        count[item.id] += item.quantity
    end
    cart.combos.each do |item|
        combo = Combo.find(item.id)
        products = JSON.parse(combo.products)
        pointer = 0
        products.each do |i|
          if i.kind_of?(Array)
            count[i[item.selected[pointer]]] += 1
            pointer += 1
          else
            count[i] += 1
          end
        end
    end
    count
  end

  def cost
    cart = JSON.parse(self.cart, object_class: OpenStruct)
    sum = 0
    cart.items.each do |item|
      sum += Product.find(item.id).cost * item.quantity
    end
    cart.combos.each do |item|
      sum += Combo.find(item.id).cost(item.selected)
    end
    sum
  end

  def total
    cart = JSON.parse(self.cart, object_class: OpenStruct)
    sum = 0
    cart.items.each do |item|
      sum += Product.find(item.id).price * item.quantity
    end
    cart.combos.each do |item|
      sum += Combo.find(item.id).price
    end
    sum
  end

  def received
    count = Hash.new(0)
    self.stocks.find_each do |stock|
      count[stock.product.id] -= stock.delta
    end
    count
  end

  def pending
    result = Hash.new(0)
    bought = self.bought
    received = self.received
    bought.each do |key, value|
      if value - received[key] > 0
        result[key] = value - received[key]
      end
    end
    result
  end

  def completed
    self.bought == self.received
  end

  # https://en.wikipedia.org/wiki/Sales_(accounting)#Other_terms
  def self.net_sales
    sum = 0
    Order.paid.find_each do |order|
      sum += order.total
    end
    sum
  end

  def self.gross_profit
    sum = 0
    Order.paid.find_each do |order|
      sum += order.total - order.cost
    end
    sum
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate
  before_action :authenticate_admin, only: :refund
  before_action :set_order, except: :index

  def index
    @orders = Order.all.order(id: :desc)
  end

  def view
    @cart = JSON.parse(@order.cart, object_class: OpenStruct)
    @customer = JSON.parse(@order.customer, object_class: OpenStruct)
  end

  def pay
    if !@order.paid_at
      @order.paid_at = Time.now
      @order.save!
      if !current_user.is_admin?
        push
      end
    end
    redirect_to view_order_path(@order)
  end

  def ship
    params[:ship].each do |key, value|
      key = Integer(key)
      value = Integer(value)
      if value > 0 and value <= @order.pending[key]
        @order.stocks.create!(product_id: key, delta: -value)
      end
    end
    redirect_to view_order_path(@order)
  end

  def refund
    @order.paid_at = nil
    @order.save!
    @order.stocks.clear
    redirect_to view_order_path(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def push
      # TODO: migrate to rails 5 and use actioncable
      uri = URI.parse('http://localhost:3000/publish')
      result = {}
      @order.bought.each do |key, value|
        result[key] = { name: Product.find(key).name, quantity: value }
      end
      params = { :counter => current_user.name, :items => result.to_json }
      uri.query = URI.encode_www_form(params)
      Net::HTTP.get(uri)
    end
end

app/views/orders/_pay_modal.html.erb
<div class="modal fade" id="payModal" tabindex="-1">
  <div class="modal-dialog modal-sm">
    <%= form_tag pay_order_path(@order), class: 'modal-content' do %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Pay By Cash</h4>
      </div>
      <div class="modal-body">
        <!-- TODO: don't believe that input[type=number]s are always positive integers -->
        <div class="form-group">
          <label class="control-label">ต้องชำระ:</label>
          <p class="form-control-static"><%= @order.total %></p>
        </div>
        <div class="form-group">
          <label for="received" class="control-label">รับมา:</label>
          <input type="number" class="form-control" id="received" ng-model="received">
        </div>
        <div class="form-group">
          <label class="control-label">ทอน:</label>
          <!-- TODO: max(change,0) -->
          <p class="form-control-static" ng-bind="received - <%= @order.total %>"></p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary" ng-disabled="received - <%= @order.total %> < 0">Pay</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/_ship_modal.html.erb
<div class="modal fade" id="shipModal" tabindex="-1">
  <div class="modal-dialog">
    <%= form_tag ship_order_path(@order), class: 'modal-content' do %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Ship</h4>
      </div>
      <div class="modal-body">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
            </tr>
          </thead>
          <tbody>
            <% @order.pending.each do |key, value| %>
              <tr>
                <td><%= product_name(key) %></td>
                <td><%= select 'ship', key, options_for_select(0..value), {}, class: 'form-control input-sm' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" onclick="$('#shipModal select option:last-child').attr('selected', true);">ALL</button>
        <button type="submit" class="btn btn-primary">Ship</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/index.haml
%h1 All Orders
%table.table
  %thead
    %tr
      %th ID
      %th Seller
      %th Customer
      %th Total
      %th Timestamp
      %th Operations
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.id
        %td= order.user.name
        %td= JSON.parse(order.customer)['name']
        %td= number_with_delimiter(order.total)
        - if order.paid_at
          %td= order.paid_at.strftime('%F %T')
        - else
          %td N/A
        %td
          = link_to(t('resources.view'), view_order_path(order))
          - if order.paid_at
            - if current_user.is_admin?
              |
              = link_to t('pos.refund'), refund_order_path(order), method: :delete, data: { confirm: "Are you sure?" }
          - else
            |
            = link_to(t('resources.edit'), edit_order_path(order))
          - if current_user.is_admin?
            |
            = t('resources.delete')

app/views/orders/view.html.erb
<div class="row" ng-app="samarnmitrPOS">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <div class="hidden-print">
      <% if @order.paid_at %>
        <button class="btn btn-info pull-left" onclick="window.print()">
          <i class="fa fa-print"></i> <%= t('pos.print') %>
        </button>
        <% if current_user.is_admin? %>
          <a href="<%= refund_order_path(@order) %>" class="btn btn-danger pull-left" data-method="delete" data-confirm="Are you sure?">
            <i class="fa fa-undo"></i> <%= t('pos.refund') %>
          </a>
        <% end %>
        <% if @order.completed %>
          <button class="btn btn-default pull-right" disabled>
            <i class="fa fa-shopping-bag"></i> <%= t('pos.all_done') %>!
          </button>
        <% else %>
          <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#shipModal">
            <i class="fa fa-shopping-bag"></i> <%= t('pos.ship') %>
          </button>
        <% end %>
      <% else %>
        <a href="<%= edit_order_path(@order) %>" class="btn btn-warning pull-left">
          <i class="fa fa-pencil"></i> <%= t('resources.edit') %>
        </a>
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#payModal">
          <i class="fa fa-usd"></i> <%= t('pos.pay') %>
        </button>
      <% end %>
    </div>
    <p class="text-center">
      <%= image_tag('smm59_logo.png', width: 300) %>
    </p>
    <h4 class="text-center">Receipt and Shipping Bill</h4>
    <hr>
    <div class="row">
      <div class="col-xs-6">
        <p>
          <strong><%= t('pos.status') %>:</strong>
          <% if @order.paid_at %>
            <% if Rails.env.production? %>
              <span class="label label-success"><%= t('pos.paid') %></span>
              <i class="fa fa-check"></i>
            <% else %>
              <span class="label label-warning"><%= t('pos.paid') %> (DEMO)</span>
              <i class="fa fa-exclamation-triangle"></i>
            <% end %>
          <% else %>
            <span class="label label-danger"><%= t('pos.not_paid') %></span>
            <i class="fa fa-times"></i>
          <% end %>
        </p>
        <p>
          <strong>Name:</strong>
          <%= @customer.name %>
        </p>
        <p>
          <strong>Contact:</strong>
          <%= @customer.info %>
        </p>
      </div>
      <div class="col-xs-6">
        <p>
          <strong>Date and Time:</strong>
          <% if @order.paid_at %>
            <%= @order.paid_at.strftime('%F %T') %>
          <% else %>
            NOT PAID
          <% end %>
        </p>
        <p>
          <strong>Order ID:</strong>
          #<%= params[:id] %>
        </p>
        <p>
          <strong>Sales:</strong>
          <%= @order.user.name %>
        </p>
      </div>
    </div>
    <table class="table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th class="text-center">#</th>
          <th>Product</th>
          <th class="text-right">Price Per Unit</th>
          <th class="text-right">Quantity</th>
          <th class="text-right">Total</th>
        </tr>
      </thead>
      <tbody>
        <!-- items in cart -->
        <% @cart.items.each_with_index do |item, index| %>
          <tr>
            <td class="text-center"><%= index + 1 %></td>
            <td><%= product_name(item.id) %></td>
            <td class="text-right">฿<%= number_with_delimiter(product_price(item.id)) %></td>
            <td class="text-right">x <%= number_with_delimiter(item.quantity) %></td>
            <td class="text-right">฿<%= number_with_delimiter(product_price(item.id) * item.quantity) %></td>
          </tr>
        <% end %>
        <!-- combos in cart -->
        <% @cart.combos.each_with_index do |item, index| %>
          <tr>
            <td class="text-center"><%= index + 1 + @cart.items.length %></td>
            <td>
              <%= combo_name(item.id) %>
              <ul>
                <% combo_items(item.id, item.selected).each do |item| %>
                  <li><%= item %></li>
                <% end %>
              </ul>
            </td>
            <td class="text-right">฿<%= number_with_delimiter(combo_price(item.id)) %></td>
            <td class="text-right">x 1</td>
            <td class="text-right">฿<%= number_with_delimiter(combo_price(item.id)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h1 class="text-right">
      Total ฿<%= number_with_delimiter(@order.total) %>
    </h1>
    <hr>
    <% if @order.paid_at && !@order.completed %>
      <h2>Back-order</h2>
      <p>กรุณานำใบนี้มารับสินค้าสำหรับสินค้าสั่งจอง Bring this receipt to pick up your pre-order item.</p>
      <table class="table table-striped table-hover table-condensed">
        <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
          </tr>
        </thead>
        <tbody>
          <% @order.pending.each do |key, value| %>
            <tr>
              <td><%= product_name(key) %></td>
              <td><%= value %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <hr>
    <% end %>
    <p class="text-center">
    กรุณาตรวจสอบสินค้าก่อนออกจากเค้าเตอร์ ไม่รับเปลี่ยนหรือคืนสินค้า<br>
    Please check the item before leaving the counter. All sales are final.<br>
    คณะกรรมการนักเรียนโรงเรียนสวนกุหลาบวิทยาลัย www.skkornor.com
    </p>
  </div>
  <% if @order.paid_at %>
    <%= render(partial: 'ship_modal') %>
  <% else %>
    <%= render(partial: 'pay_modal') %>
  <% end %>
</div>