config/routes.rb
Rails.application.routes.draw do
  root to: redirect('pos')

  get 'login' => 'session#login'
  post 'login' => 'session#auth'
  get 'logout' => 'session#logout'

  get 'orders' => 'orders#index'

  get 'pos' => 'pos#index'
  post 'pos' => 'pos#save', as: :save
  # edit
  get 'pos/edit/:id' => 'pos#edit', as: :edit_order
  # JSON
  get 'pos/products' => 'pos#products'
  get 'pos/combos' => 'pos#combos'
  # view details & print reciept
  get 'orders/:id' => 'orders#view', as: :view_order
  post 'orders/:id/pay' => 'orders#pay', as: :pay_order
  post 'orders/:id/ship' => 'orders#ship', as: :ship_order
  delete 'orders/:id/refund' => 'orders#refund', as: :refund_order

  get 'admin' => 'admin#index'

  scope 'admin' do
    get 'dashboard' => 'admin#dashboard'
    resources :users, :products, :combos, :stocks
  end

  # TODO: group together with resources:products
  get 'products/images/:id' => 'products#img', as: :product_img
  # TODO: combo_img
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :price
  scope :available, -> { where.not(hidden: true) }
  has_many :stocks

  def current_stock
    sum = 0
    self.stocks.find_each do |stock|
      sum += stock.delta
    end
    sum
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin, :admin_sidebar, except: :img
  before_action :set_product, only: [:show, :edit, :update, :destroy, :img]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  def img
    if @product.hidden
      authenticate_admin
    end
    # TODO: what if it's not a png file
    send_data @product.picture, disposition: 'inline', type: 'image/png'
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :cost, :price, :picture, :hidden)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <div class="alert alert-danger">
    <strong><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</strong>
    <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@product) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cost %>
    <%= f.number_field :cost, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :picture %>
    <!-- TODO: ... -->
    <input type="file">
  </div>
  <div class="checkbox">
    <%= f.label :hidden do %>
      <%= f.check_box :hidden %> Hidden
    <% end %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% if notice %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>

<h1>Products</h1>

<p><%= link_to 'New Product', new_product_path %></p>
<p>Total: <%= pluralize(@products.length, 'product') %></p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Cost</th>
      <th>Price</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.cost %></td>
        <td><%= product.price %></td>
        <td><img src="<%= product_img_path(product) %>" style="height:100px"></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Picture:</strong>
  <img src="<%= product_img_path(@product) %>" style="height:200px">
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>