config/routes.rb
Rails.application.routes.draw do
  root to: redirect('pos')

  get 'login' => 'session#login'
  post 'login' => 'session#auth'
  get 'logout' => 'session#logout'

  get 'orders' => 'orders#index'

  get 'pos' => 'pos#index'
  post 'pos' => 'pos#save', as: :save
  # edit
  get 'pos/edit/:id' => 'pos#edit', as: :edit_order
  # JSON
  get 'pos/products' => 'pos#products'
  get 'pos/combos' => 'pos#combos'
  # view details & print reciept
  get 'orders/:id' => 'orders#view', as: :view_order
  post 'orders/:id/pay' => 'orders#pay', as: :pay_order
  post 'orders/:id/ship' => 'orders#ship', as: :ship_order
  delete 'orders/:id/refund' => 'orders#refund', as: :refund_order

  get 'admin' => 'admin#index'

  scope 'admin' do
    get 'dashboard' => 'admin#dashboard'
    resources :users, :products, :combos, :stocks
  end

  # TODO: group together with resources:products
  get 'products/images/:id' => 'products#img', as: :product_img
  # TODO: combo_img
end

app/views/layouts/_sidebar.html.erb
<ul class="nav nav-sidebar">
  <%= sidebar_item('Overview',dashboard_path) %>
</ul>
<ul class="nav nav-sidebar">
  <%= sidebar_item('Users',users_path) %>
  <%= sidebar_item('Products',products_path) %>
  <%= sidebar_item('Combos',combos_path) %>
  <%= sidebar_item('Stocks',stocks_path) %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <% if content_for?(:title) %>
      <title><%= yield :title %> - <%= t(:site_title) %></title>
    <% else %>
      <title><%= t(:site_title) %></title>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="body-with-navbar">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= root_path %>" data-no-turbolink>Samarnmitr</a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <!-- TODO: highlight active page -->
            <li><a href="<%= pos_path %>" data-no-turbolink>POS</a></li>
            <li><a href="<%= orders_path %>">Orders</a></li>
            <% if current_user.is_admin? %>
              <li><a href="<%= dashboard_path %>">Admin</a></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="<%= logout_path %>"><%= t(:logout) %></a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <% if @admin_sidebar %>
        <div class="row">
          <div class="col-md-2 sidebar">
            <%= render(partial: 'layouts/sidebar') %>
          </div>
          <div class="col-md-10 col-md-offset-2 main">
            <%= yield %>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= t(:login) %> - <%= t(:site_title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="login-container container-fluid">
      <%= yield %>
    </div>
  </body>
</html>